/**
 * Created by XuanVinh on 8/7/2017.
 */
export const GET_ALL_REMINDERS = 'GET_ALL_REMINDERS'
export const GET_ALL_REMINDERSTYPE1 = 'GET_ALL_REMINDERSTYPE1'
export const GET_LAST_5_MEMORIES = 'Get_Last_5_MEMORIES'

export const ADD_REMINDER = 'ADD_REMINDER'
export const SET_REMINDER_TYPE_1 = 'SET_REMINDER_TYPE_1'
export const EDIT_REMINDER_TYPE_1 = 'EDIT_REMINDER_TYPE_1'
export const CANCEL_REMINDER_TYPE_1 = 'CANCEL_REMINDER_TYPE_1'
export const DELETE_REMINDER = 'DELETE_REMINDER'
export const EDIT_REMINDER = 'EDIT_REMINDER'
export const ADD_MEMORY = 'ADD_MEMORY'