export default {
    tuzki1: require('../img/sticker/tuzki1.gif'),
    tuzki2: require('../img/sticker/tuzki2.gif'),
    tuzki3: require('../img/sticker/tuzki3.gif'),
    tuzki4: require('../img/sticker/tuzki4.gif'),
    tuzki5: require('../img/sticker/tuzki5.gif'),
    tuzki6: require('../img/sticker/tuzki6.gif'),
    tuzki7: require('../img/sticker/tuzki7.gif'),
    tuzki8: require('../img/sticker/tuzki8.gif'),
    tuzki9: require('../img/sticker/tuzki9.gif'),
    NuaNia1: require('../img/sticker/NuaNia1.png'),
    NuaNia2: require('../img/sticker/NuaNia2.png'),
    NuaNia3: require('../img/sticker/NuaNia3.png'),
    NuaNia4: require('../img/sticker/NuaNia4.png'),
    NuaNia5: require('../img/sticker/NuaNia5.png'),
    NuaNia6: require('../img/sticker/NuaNia6.png'),
    NuaNia7: require('../img/sticker/NuaNia7.png'),
    NuaNia8: require('../img/sticker/NuaNia8.png'),
    NuaNia9: require('../img/sticker/NuaNia9.png'),
};
